### ISSUE TITLE
Library keys changing after new IDE

### ISSUE THREAD

**Issue by htadashi** [tanaikech/Google-Apps-Script-Library-Database#1]
@tanaikech sensei, I think some of the libraries keys have changed [because of GAS new IDE](https://groups.google.com/g/google-apps-script-community/c/qhiqjGabQpI) (e.g.:  Moment.js key was `MHMchiX6c1bwSqGM1PZiW_PxhMjh3Sh48`, but now is `15hgNOjKHUG4UtyZl9clqBbl23sDvWMS8pfDJOyIapZk5RBqwL3i-rlCo`).

Do you know if there is an easy way to automatically update the database with the new keys?

**Comment by tanaikech** [comment]
Thank you for your comment. In this library, the data is retrieved from 2 database. One is from [my database](https://github.com/tanaikech/Google-Apps-Script-Library-Database/blob/master/Google-Apps-Script-Library-Database.json). Another is from [Andrew Roberts's database](https://docs.google.com/spreadsheets/d/1Lk6OClOPA8p94fspQrs8-M-W080tb244U-fWGqvnApk/edit#gid=0) The libraries in your comment are from Andrew Roberts's database. So in this case, it is required to modify it. About this, how about reporting it to [Andrew Roberts](https://github.com/andrewroberts)?

**Comment by htadashi** [comment]
Thanks! 🙇🏻‍♂️
I'll report it to him too.
